package network_info

const (
	PROTOCOL = "tcp"
	
	MAX_DATAGRAM_SIZE_BYTES = 512
	
	SENDER_IP = "localhost"
	SENDER_PORT = "12345"
	SENDER_FULL = SENDER_IP + ":" + SENDER_PORT
	
	RECEIVER_IP = "localhost"
	RECEIVER_PORT = "12345"
	RECEIVER_FULL = RECEIVER_IP + ":" + RECEIVER_PORT
)
